version: "3"
services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules ## prevents us from mounting local node modules with local folder
      - ./frontend:/app # local folder ./frontend will be mounted as /app
    environment:
      - CHOKIDAR_USEPOLLING=true ## This helps with synchronisation of changes on volume. May not be needed
  api:
    restart: always
    build: ./api
    ports:
      - "5050:5050"
    volumes:
      - ./api:/app # local folder ./api will be mounted as /app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: verystrongpassword
    volumes:
      - mongodb_data:/data/db # No './' in front of volume shows it's an internal docker volume

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: verystrongpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:verystrongpassword@mongo:27017/
    depends_on:
      - mongo

volumes:
  mongodb_data:
